# netCDF4 模組相關練習與測試

In [65]:
%matplotlib inline
import netCDF4 as nc
from netCDF4 import Dataset

# we also need these packages
import numpy as np  # processing data array
import matplotlib.pyplot as plt  # making plots
import datetime as dt
import cftime
from cftime import DatetimeGregorian

        
nc_file="/Users/wuulong/MakerBk2/QGIS/projects/Test_316/202107251400.nc"
rootgrp = nc.Dataset(nc_file)

# 觀察

In [66]:
#rootgrp
#rootgrp.variables
#print(rootgrp.variables['runR'])

       
if 1:
    flow_simulated = rootgrp.variables['flow_simulated']
        
if 1:
    analysis_time = rootgrp.variables['analysis_time'][:]
    x = rootgrp.variables['x'][:]
    y = rootgrp.variables['y'][:]
    z = rootgrp.variables['z'][:]
    crs = rootgrp.variables['crs'][:]
    print("analysis_time=%s" %(analysis_time))
    print("x=%s" %(x))
    print("y=%s" %(y))
    print("z=%s" %(z))
    print("crs=%s" %(crs))
    #print("flow=%f" %(flow_simulated[27114180,120.9339,24.4959]))
    #print("x_index=%i" %( x.index("120.9339")))
    #print("x_index=%s" %(np.where(x==120.9339)))
if 1:
    time = rootgrp.variables['time'][:] # get value of time
    time_u=rootgrp.variables['time'].units # get unit 
    time_d=nc.num2date(time,units = time_u,calendar='standard') # get date using NetCDF num2date function
    print("time=%s" %(time))
    print("time_u=%s" %(time_u))
    print("time_d=%s" %(time_d))
if 1: #某個 time 轉成 localtime
    local = nc_to_localtime(time_d[0])
    print(local.strftime("%Y%m%dT%H%M%S+8"))


analysis_time=[27119880.]
x=[120.9337 120.9339 120.9341 ... 121.3089 121.3091 121.3093]
y=[24.4957 24.4959 24.4961 ... 24.8465 24.8467 24.8469]
z=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
crs=0
time=[27114120. 27114180. 27114240. 27114300. 27114360. 27114420. 27114480.
 27114540. 27114600. 27114660. 27114720. 27114780. 27114840. 27114900.
 27114960. 27115020. 27115080. 27115140. 27115200. 27115260. 27115320.
 27115380. 27115440. 27115500. 27115560. 27115620. 27115680. 27115740.
 27115800. 27115860. 27115920. 27115980. 27116040. 27116100. 27116160.
 27116220. 27116280. 27116340. 27116400. 27116460. 27116520. 27116580.
 27116640. 27116700. 27116760. 27116820. 27116880. 27116940. 27117000.
 27117060. 27117120. 27117180. 27117240. 27117300. 27117360. 27117420.
 27117480. 27117540. 27117600. 27117660. 27117720. 27117780. 27117840.
 27117900. 27117960. 27118020. 27118080. 2711814

# 函式庫


In [67]:
#轉換時間到 datetime

from dateutil import tz
def nc_to_localtime(d):
    utc=dt.datetime(d.year, d.month, d.day, d.hour, d.minute, d.second)
    from_zone = tz.tzutc()
    to_zone = tz.tzlocal()

    utc = utc.replace(tzinfo=from_zone)

    # Convert time zone
    local = utc.astimezone(to_zone)
    #print(dt1_local.strftime("%Y%m%dT%H%M%S+8"))
    return local

def walktree(top):
    yield top.groups.values()
    for value in top.groups.values():
        yield from walktree(value)

def to_datetime(d):

    if isinstance(d, dt.datetime):
        return d
    if isinstance(d, cftime.DatetimeNoLeap):
        return dt.datetime(d.year, d.month, d.day, d.hour, d.minute, d.second)
    elif isinstance(d, cftime.DatetimeGregorian):
        return dt.datetime(d.year, d.month, d.day, d.hour, d.minute, d.second)
    elif isinstance(d, str):
        errors = []
        for fmt in (
                "%Y-%m-%d %H:%M:%S",
                "%Y-%m-%dT%H:%M:%S",
                "%Y-%m-%dT%H:%M:%SZ"):
            try:
                return dt.datetime.strptime(d, fmt)
            except ValueError as e:
                errors.append(e)
                continue
        raise Exception(errors)
    elif isinstance(d, np.datetime64):
        return d.astype(dt.datetime)
    else:
        raise Exception("Unknown value: {} type: {}".format(d, type(d))) 
d=to_datetime(time_d[0])
#dt.datetime.strptime(d, "%Y-%m-%d %H:%M:%S")
fmt="%Y%m%dT%H%M%S"
print(d.strftime(fmt))


20210721T060000


In [68]:
rootgrp

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    Conventions: CF-1.6,UGRID-0.9
    title: Wflow
    institution: Fondus.inc
    source: Delft-FEWS 
    history: Time Zero = 2021/07/25 14:00:00 GMT+8.
    references: http://www.delft-fews.com
    comment: The actual create time of writing was 2021-09-22 22:29:23 GMT+8.
    Metadata_Conventions: Unidata Dataset Discovery v1.0
    summary: Data exported from Delft-FEWS 
    date_created: 2021-09-22 22:29:23 GMT+8
    fews_implementation_version: 2018.02
    fews_patch_number: 97964
    fews_build_number: 83929
    dimensions(sizes): time(97), analysis_time(1), y(1757), x(1879)
    variables(dimensions): float64 time(time), float64 analysis_time(analysis_time), float64 y(y), float64 x(x), float64 z(y, x), int32 crs(), float32 flow_simulated(time, y, x)
    groups: 

# 資料處理與查詢

In [69]:
# data processing
def force_in(ary,idx):
    if idx<0:
        return 0
    if idx>= len(ary):
        return len(ary)-1
    return idx
    
    
flow_simulated = rootgrp.variables['flow_simulated'] # first time step (0), all levels (:)

if 0:
    rr = flow_simulated[0]
    rr1 = np.where(rr>=0.02, 2, rr)
    logic=np.logical_and(rr1>=0.01, rr1<0.02)
    rr2 = np.where(logic, 1, rr1)
    rr3 = np.where(rr2<0.01, 0, rr2)
    #rr3[rr3>0]
if 0:
    print("time_index=%s" %(np.where(time==27115200)))
    
if 0: # 某個 time，某 x,y 的 flow
    #flow_simulated[0][0][0]
    flow_simulated[0:0:0]
    pass
if 0: # 某個時間，經緯度的 flow
    #24.4957 24.4959 24.4961
    time_idx=np.searchsorted(time, 27114180)
    y_idx=np.searchsorted(y, 24.4961)
    x_idx=np.searchsorted(x, 120.9339)
    flow_simulated[time_idx][y_idx][x_idx]

if 0:
    # 某個經緯度的歷史流量
    y1=24.4961
    x1=120.9339
    y_idx=np.searchsorted(y,y1 )
    x_idx=np.searchsorted(x,x1 )

    for i in range(len(time)):
        flow = flow_simulated[i][y_idx][x_idx]
        local = nc_to_localtime(time_d[i])
        time_str=local.strftime("%Y%m%dT%H%M%S+8")
        print("%s,%f,%f = %f" %(time_str,y1,x1,flow))
if 0:
    max_v = np.max(flow_simulated)
    print("max=%f" %(max_v))

    
if 0:
    y1=24.4961
    x1=120.9339
    left=x1-0.001
    right=x1+0.001
    top=y1+0.001
    bottom=y1-0.001

    top_idx=np.searchsorted(y,top )
    bottom_idx=np.searchsorted(y,bottom )
    left_idx=np.searchsorted(x,left )
    right_idx=np.searchsorted(x,right )
    print("top_idx=%i,bottom_idx=%i,left_idx=%i,right_idx=%i" %(top_idx,bottom_idx,left_idx,right_idx))

if 0: # 某個點附近一定範圍內最高流量
    y1=24.4961
    x1=120.9339
    o=5 #offset_idx
    y_idx=np.searchsorted(y,y1)
    x_idx=np.searchsorted(x,x1)
    print("y_idx=%i,x_idx=%i" %(y_idx,x_idx))
    area = flow_simulated[:,force_in(y,y_idx-o):force_in(y,y_idx+o),force_in(x,x_idx-o):force_in(x,x_idx+o)]
    area_max=np.max(area)
    print("max=%f" %(area_max))




# netcdf4 建 dataset 範例

In [70]:
#netcdf4 建 dataset 範例
if 1:#group
    rootgrp = Dataset("test.nc", "w")
    #rootgrp = Dataset("test.nc", "r",format="NETCDF4")
    fcstgrp = rootgrp.createGroup("forecasts")
    analgrp = rootgrp.createGroup("analyses")
    fcstgrp1 = rootgrp.createGroup("/forecasts/model1")
    fcstgrp2 = rootgrp.createGroup("/forecasts/model2")
    print(rootgrp.groups)
if 1: #dimension
    level = rootgrp.createDimension("level", None)
    time = rootgrp.createDimension("time", None)
    lat = rootgrp.createDimension("lat", 73)
    lon = rootgrp.createDimension("lon", 144) 
    print(rootgrp.dimensions)
if 1: #variable
    times = rootgrp.createVariable("time","f8",("time",))
    levels = rootgrp.createVariable("level","i4",("level",))
    latitudes = rootgrp.createVariable("lat","f4",("lat",))
    longitudes = rootgrp.createVariable("lon","f4",("lon",))
    # two dimensions unlimited
    temp = rootgrp.createVariable("temp","f4",("time","level","lat","lon",))
    temp.units = "K"

    ftemp = rootgrp.createVariable("/forecasts/model1/temp","f4",("time","level","lat","lon",))
if 1: #Attributes in a netCDF file
    import time
    rootgrp.description = "bogus example script"
    rootgrp.history = "Created " + time.ctime(time.time())
    rootgrp.source = "netCDF4 python module tutorial"
    latitudes.units = "degrees north"
    longitudes.units = "degrees east"
    levels.units = "hPa"
    temp.units = "K"
    times.units = "hours since 0001-01-01 00:00:00.0"
    times.calendar = "gregorian"
if 1:
    lats =  np.arange(-90,91,2.5)
    lons =  np.arange(-180,180,2.5)
    latitudes[:] = lats
    longitudes[:] = lons
    print("latitudes =\n{}".format(latitudes[:]))    
if 1: # append along two unlimited dimensions by assigning to slice.
    nlats = len(rootgrp.dimensions["lat"])
    nlons = len(rootgrp.dimensions["lon"])
    print("temp shape before adding data = {}".format(temp.shape))

    from numpy.random import uniform
    temp[0:5, 0:10, :, :] = uniform(size=(5, 10, nlats, nlons))
    print("temp shape after adding data = {}".format(temp.shape))

    # levels have grown, but no values yet assigned.
    print("levels shape after adding pressure data = {}".format(levels.shape))

    # now, assign data to levels dimension variable.
    levels[:] =  [1000.,850.,700.,500.,300.,250.,200.,150.,100.,50.]
if 1:
    #Dealing with time coordinates
    # fill in times.
    from datetime import datetime, timedelta
    from cftime import num2date, date2num
    dates = [datetime(2001,3,1)+n*timedelta(hours=12) for n in range(temp.shape[0])]
    times[:] = date2num(dates,units=times.units,calendar=times.calendar)
    print("time values (in units {}):\n{}".format(times.units, times[:]))
    dates = num2date(times[:],units=times.units,calendar=times.calendar)
    print("dates corresponding to time values:\n{}".format(dates))
if 0:
    rootgrp.close()
    


{'forecasts': <class 'netCDF4._netCDF4.Group'>
group /forecasts:
    dimensions(sizes): 
    variables(dimensions): 
    groups: model1, model2, 'analyses': <class 'netCDF4._netCDF4.Group'>
group /analyses:
    dimensions(sizes): 
    variables(dimensions): 
    groups: }
{'level': <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'level', size = 0, 'time': <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'time', size = 0, 'lat': <class 'netCDF4._netCDF4.Dimension'>: name = 'lat', size = 73, 'lon': <class 'netCDF4._netCDF4.Dimension'>: name = 'lon', size = 144}
latitudes =
[-90.  -87.5 -85.  -82.5 -80.  -77.5 -75.  -72.5 -70.  -67.5 -65.  -62.5
 -60.  -57.5 -55.  -52.5 -50.  -47.5 -45.  -42.5 -40.  -37.5 -35.  -32.5
 -30.  -27.5 -25.  -22.5 -20.  -17.5 -15.  -12.5 -10.   -7.5  -5.   -2.5
   0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25.   27.5
  30.   32.5  35.   37.5  40.   42.5  45.   47.5  50.   52.5  55.   57.5
  60.   62.5  65.   67.5  70.   72.5  75

# 觀察自建

In [71]:
if 0:
    for children in walktree(rootgrp):
        for child in children:
            print(child)
if 0:
    for name in rootgrp.ncattrs():
        print("Global attr {} = {}".format(name, getattr(rootgrp, name)))